# Copyright (c) 2026 paidaxin-12138
# Licensed under CC BY-NC 4.0 — see LICENSE in repository root.
# https://creativecommons.org/licenses/by-nc/4.0/
"""实时聊天 — 色板与渲染常量（统一引用 apple_ui_tokens）。"""
from __future__ import annotations

from ui import apple_ui_tokens as UI

# 布局 / 分页
DEFAULT_PAGE_SIZE = 50
MSG_RENDER_BATCH = 4
MSG_RENDER_INTERVAL_MS = 60
MSG_LOADING_MIN_MS = 1500

# 背景与边框
C_BG = UI.BG_PRIMARY
C_CHAT_BG = C_BG
C_PANEL = UI.BG_SECONDARY
C_CARD = UI.BG_SECONDARY
C_BORDER = UI.BORDER
C_TEXT = UI.TEXT_PRIMARY
C_MUTED = UI.TEXT_SECONDARY
C_DIM = UI.TEXT_TERTIARY
C_ACCENT = UI.ACCENT
C_LOADING = UI.ACCENT
C_GREEN = UI.SUCCESS
SUCCESS = UI.SUCCESS
WARNING = UI.WARNING
ERROR = UI.ERROR

# 气泡
B_BUBBLE_RADIUS = "18px"
B_BUBBLE_TAIL_RADIUS = "8px"
B_SYSTEM_RADIUS = "14px"
C_BUBBLE_FRAME_SELF = UI.BG_TERTIARY
C_SYSTEM_BG = UI.BG_TERTIARY
C_SYSTEM_TEXT = UI.TEXT_TERTIARY
C_TIME_TEXT = UI.TEXT_SECONDARY
C_AI_BUBBLE = UI.ACCENT_SURFACE
C_MSG_BODY = UI.TEXT_PRIMARY

# 输入区 chrome
C_CHROME_BG = UI.BG_TERTIARY
C_CHROME_HOVER = UI.BG_HOVER
C_CHROME_BORDER = UI.BORDER
C_CHROME_PRESSED = UI.BG_ELEVATED
